---
- name: Lab2 - Delete a node using internal variables
  hosts: all
  connection: local
  vars:
   user: admin
   password: adminadmin

  tasks:
     - name: Delete node using bigip_node module
       bigip_node:
          server: "{{ inventory_hostname }}"
          user: "{{ user }}"
          password: "{{ password }}"
          validate_certs: no
          state: absent
          name: "Server1"
       delegate_to: localhost

